apiVersion: apps/v1
kind: Deployment
metadata:
  name: postman-echo-ballerina
  labels:
    app: postman-echo-ballerina
spec:
  selector:
    matchLabels:
      app: postman-echo-ballerina
  replicas: 1
  template:
    metadata:
      labels:
        app: postman-echo-ballerina
    spec:
      containers:
        - name: postman-echo-ballerina
          image: docker.io/supiri/postman-echo-ballerina:latest
          ports:
            - name: http
              containerPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: postman-echo-ballerina
spec:
  #type: NodePort
  selector:
    app: postman-echo-ballerina
  ports:
    - port: 80
      targetPort: http