apiVersion: apps/v1
kind: Deployment
metadata:
  name: http2-server-go
  labels:
    app: http2-server-go
spec:
  selector:
    matchLabels:
      app: http2-server-go
  replicas: 1
  template:
    metadata:
      labels:
        app: http2-server-go
    spec:
      containers:
        - name: http2-server-go
          image: docker.io/supiri/http2-server-go:latest
          ports:
            - name: http
              containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: http2-server-go
spec:
  #type: NodePort
  selector:
    app: http2-server-go
  ports:
    - port: 80
      targetPort: http